version: 2
updates:
  - package-ecosystem: maven
    directory: /micro-course-api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /micro-course-admin
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
